### ISSUE TITLE
gtk.Builder.AddFromString throws SIGSEGV.

### ISSUE THREAD

**Issue by Kyras** [gotk3/gotk3#250] opened 2018-03-06 10:28 UTC
SIGSEGV is thrown from the method, if `gtk.Init` was not called beforehand, which leads to fun times if you try to use `gtk.Builder` with `gtk.Application`, as you are expected not to call `gtk.Init`.

Short snippet:
```go
package main

import (
	"log"

	"github.com/gotk3/gotk3/gtk"
)

const template string = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.20.3 -->
<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkWindow" id="Window"/>
</interface>
`

func main() {
	// gtk.Init(&os.Args)
	if builder, err := gtk.BuilderNew(); err != nil {
		log.Fatal(err)
	} else if err := builder.AddFromString(template); err != nil {
		log.Fatal(err)
	} else if winObj, err := builder.GetObject("Window"); err != nil {
		log.Fatal(err)
	} else {
		window := winObj.(*gtk.Window)
		window.ShowAll()
	}
	// gtk.Main()
}
```

I am pretty new to the GTK programming, so it is possible I am using the combination of `gtk.Application` and `gtk.Builder` wrongly. But anyways, `builder.AddFromString` should return error instead of runtime panic.

FIX1: Fixed typo.

**Comment by jhekasoft** [comment] 2018-03-24 15:10
I have some issue with gtk.AddFromFile() and gtk.BuilderNewFromFile().

**Comment by tommyshem** [comment] 2018-04-25 01:49
@Kyras 
I am also new to gtk programming, I don't know if you got the code working but below is a working program if you are interested.
```go
package main

import (
	"log"
	"os"

	"github.com/gotk3/gotk3/glib"
	"github.com/gotk3/gotk3/gtk"
)

const template string = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.22.1 -->
<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkWindow" id="Window">
    <property name="can_focus">False</property>
    <property name="title" translatable="yes">Gtk3 Simple Application using Builder</property>
    <property name="default_width">600</property>
    <property name="default_height">400</property>
    <property name="icon_name">face-monkey</property>
    <child>
      <placeholder/>
    </child>
    <child>
      <object class="GtkLabel" id="label1">
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="label" translatable="yes">Hello World!</property>
      </object>
    </child>
  </object>
</interface>
`

func main() {
	// Create Gtk Application, change appID to your application domain name reversed.
	const appID = "org.gtk.example"
	application, err := gtk.ApplicationNew(appID, glib.APPLICATION_FLAGS_NONE)
	// Check to make sure no errors when creating Gtk Application
	if err != nil {
		log.Fatal("Could not create application.", err)
	}

	application.Connect("activate", func() {
		// load ui from string
		if builder, err := gtk.BuilderNew(); err != nil {
			log.Fatal("Could not create builder.", err)
		} else if err := builder.AddFromString(template); err != nil {
			log.Fatal("Builder could not load ui.", err)
		} else if winObj, err := builder.GetObject("Window"); err != nil {
			log.Fatal("Could not find object in builder.", err)
		} else {
			window := winObj.(*gtk.Window)
			window.ShowAll()
			application.AddWindow(window)
		}
	})
	// Run Gtk application
	application.Run(os.Args)
}
```

**Comment by Northern-Lights** [comment] 2018-11-25 07:11
Looks like the key is that the XML must be added to the builder under the context of the application's "activate" callback.

**Comment by Bios-Marcel** [comment] 2018-11-25 13:11
@Kyras What exactly is the problem when running your code with `gtk.Init(...)` and `gtk.Main()` uncommented? I have just tested it and it works fine for me. I also see no reason to not use those two, as they are required to initialize GTK and start the main loop. Would be nice if you could clarify what exactly the problem is.

**Comment by Kyras** [comment] 2018-11-25 13:18
As show in actual example of GTK(https://developer.gnome.org/gtk3/stable/gtk-getting-started.html). You are not expected to call `gtk.Init` nor `gtk.Main`, _as stated in original comment_. As this is a binding, there is no documentary of this discrepancy from the original library.

The second thing is, nonetheless you run this application, **it should not panic at runtime** but rather, return an error, again _as stated in original comment_.

**Comment by Bios-Marcel** [comment] 2018-11-25 13:39
I see, I wasn't able to parse that, sorry. But yes, you are right, it shouldn't panic.

**Comment by Bios-Marcel** [comment] 2018-11-26 12:20
Since this panic could theoretically occur after any gtk call, I don't see how to avoid it without adding a ton of boilerplate. Therefore I'd rather close this as `wontfix`.

**Closed** 2020-02-13 20:37 UTC
Labels: bug, documentation, wontfix
