### ISSUE TITLE
Could not determine kind of name for C.free

### ISSUE THREAD

**Issue by rasteric** [gotk3/gotk3#444] opened 2019-10-01 09:32 UTC
After the latest pull requests were merged in I get this error. It worked fine before.

```
go build -o planner -tags "gtk_3_18 sqlite_fts5" *.go
# github.com/gotk3/gotk3/gtk
../../../../pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190930052053-f6994e9a1558/gtk/gtk_since_3_16.go:158:8: could not determine kind of name for C.free

```
My system is Linux Mint 18.3 with Gtk 3.18 installed.

**Comment by hfmrow** [comment] 2019-10-01 17:54
Hi,
I can't reproduce your issue, so i cannot test my idea ...
If you want to try something,
open this file: `gtk_since_3_16.go`
add the following `// #include <stdlib.h>` just before `// #include <gtk/gtk.h>`
like this:
```
package gtk

// #include <stdlib.h>
// #include <gtk/gtk.h>
// #include "gtk_since_3_16.go.h"
import "C"
```
**Notice**: You seems using modules. So for testing purpose you must disable this functionality otherwise, modification of the source will not be well considered (versioning not match original repos).
The steps are: 
- Disabling modules
- Loading library "go get ..."
- Install path must be "$GOPATH/github.com/gotk3/gotk3" and not "_**../../../../pkg/mod**_/github.com/gotk3/gotk3"
- Modify the file ( "$GOPATH/github.com/gotk3/gotk3/gtk_since_3_16.go") as indicated and try to compile you application.

Let me know if it works, if it does, I'll do a PR to signify it. (or you can do it, as you wish)

**Explanation**:
C.free is a command contained into <stdlib.h> in C language: https://www.tutorialspoint.com/c_standard_library/stdlib_h.htm (Library functions, 8 )

**Comment by rasteric** [comment] 2019-10-01 18:32
Sorry, because of the issue, I've just upgraded 'in place' from Linux Mint 18 to Linux Mint 19 (no risk, no fun!), which uses GTK 3.22 instead of 3.18. After recompilation in the new environment, the error no longer occurs. So now I cannot test your solution any longer. I'm closing this issue, which seems to only occur with older versions of GTK3.

Thanks a lot for the help!

**Comment by hfmrow** [comment] 2019-10-01 18:48
ok, the main thing is that it works now, and besides, you will have the improvements of 3.22. Have fun.

**Comment by wrycode** [comment] 2019-10-07 04:18
I encountered this issue while trying to build from a Fedora container (cross-compiling for Windows). @hfmrow your suggestion to add `// #include <stdlib.h>`  works. Is there a reason it's not included already?

I'm trying to set up a script for automated builds but I'd rather not use sed hacks on the gotk3 code itself.

**Comment by hfmrow** [comment] 2019-10-07 11:53
Hi,
> Is there a reason it's not included already?

As you can see, it does not appear in the C import library list for this file, but the behaviour remains strange. it is included in the main file "gtk.go". I do not understand why, in some cases, this problem arises and some other cases, there is no issue.

Before last merge session, it's included but it was removed for unknown reason ...
If you confirm that solution solve your issue, you can make a pull request for it.

**Comment by rasteric** [comment] 2019-10-07 14:24
I'm reopening the issue, since it seems to occur in certain configurations.

**Comment by wrycode** [comment] 2019-10-08 03:13
I can confirm that it solves my issue, but I'm not positive that it's really a bug in gotk3. The library builds just fine on my Arch Linux installation without this line, so maybe older versions of Go or GCC have something to do with it.

**Comment by rasteric** [comment] 2019-10-08 07:44
I got the error on Linux Mint 18.3 with the GTK 3.18 flag for compilation, and no longer get it in Linux Mint 19 which uses GTK 3.22, with the same version of Go installed (it was an in-place upgrade). So it doesn't seem to be caused by Go itself. Maybe GCC.

**Comment by wrycode** [comment] 2019-10-15 23:26
This issue can be closed.

**Comment by founderio** [comment] 2020-02-12 01:52
Ping @andre-hub please close this ;)

**Closed** 2020-02-12 06:12 UTC
