### ISSUE TITLE
[BUG] Does not support the latest version of gilb2

### ISSUE THREAD

**Issue by twgh** [gotk3/gotk3#807] opened 2021-07-18 09:24 UTC
I hope that the author will update the support for the latest version of gilb2. Currently, even the examples cannot be run.
```
# github.com/gotk3/gotk3/glib
cgo-gcc-prolog: In function '_cgo_26ff448d08b0_Cfunc_g_binding_get_source':
cgo-gcc-prolog:71:2: warning: 'g_binding_get_source' is deprecated: Use 'g_binding_dup_source' instead [-Wdeprecated-declarations]
In file included from C:/msys64/mingw64/include/glib-2.0/glib-object.h:22,
                 from C:/msys64/mingw64/include/glib-2.0/gio/gioenums.h:28,
                 from C:/msys64/mingw64/include/glib-2.0/gio/giotypes.h:28,
                 from C:/msys64/mingw64/include/glib-2.0/gio/gio.h:26,
                 from ..\..\..\pkg\mod\github.com\gotk3\gotk3@v0.6.1\glib\gbinding.go:3:
C:/msys64/mingw64/include/glib-2.0/gobject/gbinding.h:112:23: note: declared here
  112 | GObject *             g_binding_get_source          (GBinding *binding);
      |                       ^~~~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: In function '_cgo_26ff448d08b0_Cfunc_g_binding_get_target':
cgo-gcc-prolog:107:2: warning: 'g_binding_get_target' is deprecated: Use 'g_binding_dup_target' instead [-Wdeprecated-declarations]
In file included from C:/msys64/mingw64/include/glib-2.0/glib-object.h:22,
                 from C:/msys64/mingw64/include/glib-2.0/gio/gioenums.h:28,
                 from C:/msys64/mingw64/include/glib-2.0/gio/giotypes.h:28,
                 from C:/msys64/mingw64/include/glib-2.0/gio/gio.h:26,
                 from ..\..\..\pkg\mod\github.com\gotk3\gotk3@v0.6.1\glib\gbinding.go:3:
C:/msys64/mingw64/include/glib-2.0/gobject/gbinding.h:116:23: note: declared here
  116 | GObject *             g_binding_get_target          (GBinding *binding);
```

**Comment by twgh** [comment] 2021-07-19 07:15
Try to manually install the old version of glib2.
Download the old version here: [https://archive.archlinux.org/packages/g/glib2/](url)
```
# pacman -U D:/glib2-2.66.7-1-x86_64.pkg.tar.zst
loading packages...
error: 'D:/glib2-2.66.7-1-x86_64.pkg.tar.zst': invalid or corrupted package (PGP signature)
```
I can't solve it...

**Comment by CHchenf** [comment] 2021-08-16 10:40
glib2 needs to solve the problem of multiple dependencies, which is a headache. Personally, I think it would be better to uninstall the whole msys environment and reinstall it!

Of course, if you are Daniel, you can ignore this little white problem, ha ha!

Otherwise, it is really not recommended for novices to try to downgrade the installed glib version, which will seriously hurt your confidence in learning and trying gtk3 package!

**Comment by CHchenf** [comment] 2021-08-17 03:09
![image](https://user-images.githubusercontent.com/19359167/129657704-1fb8e5eb-7280-4f5b-b019-b8eb56ff8b7e.png)

**Comment by zpfz** [comment] 2021-08-18 06:50
> glib2 needs to solve the problem of multiple dependencies, which is a headache. Personally, I think it would be better to uninstall the whole msys environment and reinstall it!
> 
> Of course, if you are Daniel, you can ignore this little white problem, ha ha!
> 
> Otherwise, it is really not recommended for novices to try to downgrade the installed glib version, which will seriously hurt your confidence in learning and trying gtk3 package!

大哥，烦请教下如果控制 glib 版本呢？

**Comment by CHchenf** [comment] 2021-08-19 06:13
木有办法控制版本哦，我是修改的那几行代码解决的。我安装的是最新的版本和代码。

Feng L.H. ***@***.***> 于2021年8月18日周三 下午2:51写道：

**Comment by sqp** [comment] 2021-08-21 21:06
Those are deprecation **warnings**, not bugs.
They're just here to inform devs that those functions will have to be replaced in the future (generally for the next major version, as most libs ensure they don't remove or change features during a major version lifecycle (they just add things and warn about things to be removed)).

**Comment by MJacred** [comment] 2021-09-12 08:15
@andre-hub: duplicate of #762

**Closed** 2021-10-09 01:27 UTC
Labels: bug
